CREATE DATABASE IF NOT EXISTS `usuarios` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS `peliculas` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS `productos` DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;